# path or URL to sample sheet (TSV format, columns: sample, condition, ...)
samples: config/samples.tsv
# path or URL to sequencing unit sheet (TSV format, columns: sample, unit, fq1, fq2)
# Units are technical replicates (e.g. lanes, or resequencing of the same biological
# sample).
units: config/units.tsv


ref:
  # Ensembl species name
  species: homo_sapiens
  # Ensembl release (make sure to take one where snpeff data is available, check 'snpEff databases' output)
  release: 100
  # Genome build
  build: GRCh38

trimming:
  activate: False

pca:
  activate: True
  labels:
    # columns of sample sheet to use for PCA
    - condition

diffexp:
  # contrasts for the deseq2 results method
  contrasts:
    A-vs-B:
      - untreated
      - treated
  model: ~condition

params:
  cutadapt-pe: ""
  cutadapt-se: ""
  star: ""

### bam2bakR parameters ###

# Type of mutations of interest
mut_tracks: "TC" # ("TC", "GA", "TC,GA")

# Minimum base quality to call mutation
minqual: 40

# Which columns to keep in final cB.csv.gz file
keepcols: "sample,sj,io,ei,ai,GF,XF,rname"

# String common to spike-in gene_ids in annotation gtf
  # If you have no spike-ins, then this should be "\"\"", i.e., a string containing ""
spikename: "\"\""

# If True, tracks will be normalized using either spike-ins (if present) or edgeR's normalization strategy
normalize: True

# Are you using the Windows subsystem for linux? 0 = Yes, 1 = No
WSL: 1